#include<iostream>
#include "MS_CLNG.h"
#include "BSD_CLNG.h"



using namespace std;

int main()
{
    BSD_CLNG bclng(1016404597,12345,2147483648,0);
    MS_CLNG  mclng(214013,2531011,2147483648,0);
   
    
    //generating 20 random numbers by BCD method
    
    cout << "20 Random Numbers generated by BSD method  \n";
    for (int i = 0; i < 20; i++)
    {
        
        cout << bclng.getRandomNumber()<< " \n";
    }
    
    cout << endl;
      cout << "20 Random Numbers generated by Microsoft method \n";
    //generating 20 random bits my microsoft method
    for (int i = 0; i < 20; i++)
    {
       
        cout << mclng.getRandomNumber() << " \n";
    }

    return 0;
}
